#Datenacquise
data-acquisition:
    environment:
        CONSUMER_KEY: "${CK}"
        CONSUMER_SECRET: "${CS}"
        ACCESS_TOKEN: "${AT}"
        ACCESS_TOKEN_SECRET: "${ATS}"
        DEBUGGING: "${DEBUGGING}"
        DATABASE_REST_URL: "http://data-management:3000"
    image: mip02/data-acquisition
    links:
        - data_management:data-management

#Data management
data_management:
    image: mip02/data_management
    links:
        - analysis-rest

#Data analysis
analysis-rest:
    image: mip02/analysis-rest
    environment:
        MONGODB_PASS: "${ANALYSIS_MONGODB_PASS}"
    ports:
     - "5000:5000"
    links:
     - analysis-database:mongodb
     - analysis-cache:redis

analysis-database:
    image: mip02/analysis-database
    environment:
        MONGODB_USER: "analysis"
        MONGODB_DATABASE: "analysis"
        MONGODB_PASS: "${ANALYSIS_MONGODB_PASS}"
    volumes:
        - /data/db
    ports:
        - "27017:27017"
        - "28017:28017"

analysis-cache:
    image: mip02/analysis-cache
    ports:
     - "6379:6379"

analysis-preprocess:
    image: mip02/analysis-preprocess
    links:
     - analysis-database:mongodb

#demo frontend
analysis-query-test:
  build: https://github.com/haw-mip02/analysis-query-test.git
  ports:
    - "443:9000"
  environment:
    #REST_URL: "${ANALYSIS_REST_URL}"
    REST_URL: "http://hqor.de:16500/analysis/v1.0/"

#Frontend
frontend:
    image: mip02/frontend
    ports:
      - "80:80"
    links:
      - analysis-rest


#Watchtower
watchtower:
    image: webhippie/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
