#Datenacquise
data-acquisition:
    environment:
        CONSUMER_KEY: "${CK}"
        CONSUMER_SECRET: "${CS}"
        ACCESS_TOKEN: "${AT}"
        ACCESS_TOKEN_SECRET: "${ATS}"
    image: mip02/data-acquisition




#Data management
data_management:
    image: mip02/data_management
    links:
        - analysis-rest




#Data analysis
analysis-rest:
    image: mip02/analysis-rest

analysis-database:
    image: mip02/analysis-database

analysis-cache:
    image: mip02/analysis-cache

analysis-preprocess:
    image: mip02/analysis-preprocess
    



#Frontend
frontend:
    image: mip02/frontend
